title: Artorius
description: Arthur's Blog

url: http://artori.us
paginate_path: "posts/:num/"
permalink: :title/

markdown: redcarpet
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url:
 - title: Github
   url: https://github.com/Arthraim
 - title: Twitter
   url: https://twitter.com/arthraim
 - title: Medium
   url: https://medium.com/@arthurwxy

social:
   github: arthraim
   twitter: arthraim
   email: arthraim@gmail.com

google_analytics: "UA-8352384-7"
