title: Artorius
description: Arthur's Blog

url: https://artori.us
paginate_path: "posts/:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: Articles
   url: /articles
 - title: Blogroll
   url: /blogroll
 - title: JIKE
   url: https://web.okjike.com/user/F65E8535-A827-4B75-8583-EFD4EB5C2671/post
 - title: Github
   url: https://github.com/Arthraim
 - title: Twitter
   url: https://twitter.com/arthraim
 - title: Medium
   url: https://medium.com/@arthurwxy

social:
   github: arthraim
   twitter: arthraim
   email: arthraim@gmail.com

google_analytics: "UA-8352384-7"

gems: [jekyll-paginate]
