name: Artorius
description: Arthur's Blog

url: http://artori.us
paginate_path: "posts/:num/"
permalink: :title/

markdown: redcarpet
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url:
